// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateServer(arg1:main.ApiServer):void;

export function FindServer(arg1:string):Promise<main.ApiServer>;

export function LaunchServer(arg1:string):void;

export function LoadServers():Promise<Array<main.ApiServer>>;

export function UpdateServer(arg1:main.ApiServer):void;
