// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function FindServer(arg1) {
  return window['go']['main']['App']['FindServer'](arg1);
}

export function LaunchServer(arg1) {
  return window['go']['main']['App']['LaunchServer'](arg1);
}

export function LoadServers() {
  return window['go']['main']['App']['LoadServers']();
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
